### PR TITLE
Some changes made during integration into SwiftLint

### PR DESCRIPTION
**Pull request by xzeror**
Hi!

Made some improvements. Could you please merge and tag new version of your library?

Thanks!

### CODE REVIEW

**Review by Bouke — CHANGES_REQUESTED** [review]
Overall the changes look good. However the tests appear to be failing on Linux, any idea why that might be the case? 

Furthermore your PR changes the indentation to a TAB, which is obviously wrong 😉. Please revert back to 4 spaces 👾.

**Comment by xzeror** [comment]
I guess the reason tests fails on Linux is that it's not possible to create directory, so self.tmpDir is effectively has null and unable to be dereferenced by Swift runtime.

**Comment by Bouke** [comment]
Ah darn, I missed the failing test. Could you look into resolving that issue? If that's resolved, I can tag the package with a new version.

**Comment by Bouke** [comment]
I've made some additional changes. It looks like Linux support isn't completely flushed out, with half of the tests still failing.

**Pull request merged**
